# Company Information
company_name: Adassa
domain_name: adassa.com.jm
address_line: Kingston
country: Jamaica
company_email: mail@adassa.com.jm
description: This is the AES, Inc. website.
meta_description: business management system, engineering, information technology, personal development, personal products

# Site Information
title: Adassa
author: Desmond Bennett
baseurl: ""
url: https://adassa.com.jm
permalink: pretty

# Social Links
facebook_link: https://www.facebook.com/desmondpbennett
twitter_link: https://twitter.com/DPB_and_A
github_link: https://github.com/Adassa-Enterprise-Solutions/

disqus: false
disqus_shortname: adassa

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate-v2

jekyll_admin:
  hidden_links:
    - configuration
  homepage: "pages"  
  